### ISSUE TITLE
ConvertPublicKey + SharedKey

### ISSUE THREAD

**Issue by redDwarf03** [Tougee/curve25519#1]
Hello
thanks for your work

I would like to use your library to translate this js code:

```
const { public: ephemeralPublicKey, private: ephemeralPrivateKey} = curve25519.generateKeyPair(randomBytes(32))  
const curve25519pub = ed2curve.convertPublicKey(pubBuf)

var sharedKey = curve25519.sharedKey(ephemeralPrivateKey, curve25519pub)
```

But I don't know how.
Is it possible with your library ?

Best

**Comment by Tougee** [comment]
This library provides these 2 APIs you can use, `generateKeyPair()` and `X25519()` as `shareKey()`.
Not sure of `const curve25519pub = ed2curve.convertPublicKey(pubBuf)`, any full implementation codes of this?

**Comment by redDwarf03** [comment]
here's:
https://github.com/archethic-foundation/libjs/blob/b2b22f79d91bd88d7afd9828c536af930f4c7f19/lib/crypto.js#L286

ed2curve documentation: https://www.npmjs.com/package/ed2curve

**Comment by Tougee** [comment]
Not have these APIs yet.

**Comment by redDwarf03** [comment]
ok. thank you for your answer
Best

**Comment by Tougee** [comment]
If you're using [Ed25519](https://github.com/tougee/ed25519), you can get codes here.
